EXPENSE_CATEGORY_INDICATOR = "Expense"
MONTHS = [
  "January", "February", "March", "April", "May", "June","July",
  "August", "September", "October", "November", "December"
]

// These are within the summary sheets
SUMMARY_SHEET_SUB_NAME = "Summary";
SUMMARY_MONTHLY_SHEET_NAME = "Monthly Summary";
SUMMARY_YEARLY_SHEET_NAME = "Yearly Summary";
SUMMARY_INCOME_EXPENSES_TEXT_SEPARATOR = "Expenses";
SUMMARY_TOTALS_TEXT = "Totals";
SUMMARY_MONTH_ROW_NUMBER = 4;
SUMMARY_MONTH_COLUMN_NUMBER = 8;
SUMMARY_MONTH_COLUMN = "H";
SUMMARY_MONTH_ROW = "4";
SUMMARY_CATEGORY_NAME_COLUMN_LETTER = "B";
SUMMARY_CATEGORY_NAME_COLUMN_NUMBER = 2;
SUMMARY_CATEGORY_NAME_COLUMN_INDEX = SUMMARY_CATEGORY_NAME_COLUMN_NUMBER - 1;
SUMMARY_CATEGORY_NAME_COLUMN_HEIGHT = 1;
SUMMARY_CATEGORY_NAME_COLUMN_WIDTH = 4;
SUMMARY_CATEGORY_PLANNED_COLUMN_LETTER = "F";
SUMMARY_CATEGORY_PLANNED_COLUMN_NUMBER = 6;
SUMMARY_CATEGORY_PLANNED_COLUMN_INDEX = SUMMARY_CATEGORY_PLANNED_COLUMN_NUMBER - 1;
SUMMARY_CATEGORY_ACTUAL_COLUMN_LETTER = "G";
SUMMARY_CATEGORY_ACTUAL_COLUMN_NUMBER = 7;
SUMMARY_CATEGORY_ACTUAL_COLUMN_INDEX = SUMMARY_CATEGORY_ACTUAL_COLUMN_NUMBER - 1;
SUMMARY_CATEGORY_DIFFERENCE_COLUMN_NUMBER = 8;
SUMMARY_CATEGORY_DIFFERENCE_COLUMN_INDEX = SUMMARY_CATEGORY_DIFFERENCE_COLUMN_NUMBER - 1;

// These are the names of the data sheets
DATA_EXPENSE_SHEET_NAME = "CategoryExpenseData";
DATA_INCOME_SHEET_NAME = "CategoryIncomeData";
DATA_ACCOUNT_SHEET_NAME = "AccountData";
DATA_CATEGORY_SHEET_COLUMN_COUNT = 13;
DATA_CATEGORY_SHEET_COLUMN_LETTER = "M";
DATA_CATEGORIES_START_ROW_NUMBER = 2;
DATA_ACCOUNTS_START_ROW_NUMBER = 1;
DATA_CATEGORY_NAME_COLUMN_LETTER = "A";
DATA_CATEGORY_NAME_COLUMN_NUMBER = 1;
DATA_ACCOUNT_NAME_COLUMN_LETTER = "A";
DATA_ACCOUNT_NAME_COLUMN_NUMBER = 1;

// These are within the monthly transaction sheets
TRANSACTION_EXPENSES_CATEGORY_COLUMN_LETTER = "F";
TRANSACTION_EXPENSES_AMOUNT_COLUMN_LETTER = "E";
TRANSACTION_EXPENSES_ACCOUNT_COLUMN_LETTER = "D";
TRANSACTION_INCOME_CATEGORY_COLUMN_LETTER = "L";
TRANSACTION_INCOME_AMOUNT_COLUMN_LETTER = "K";
TRANSACTION_INCOME_ACCOUNT_COLUMN_LETTER = "J";
TRANSACTION_HEADER_ROW_COUNT = 5;
TRANSACTION_EXPENSES_START_COLUMN_LETTER = "B";
TRANSACTION_EXPENSES_END_COLUMN_LETTER = "F";
TRANSACTION_INCOME_START_COLUMN_LETTER = "H";
TRANSACTION_INCOME_END_COLUMN_LETTER = "L";
TRANSACTION_EXPENSES_DATE_COLUMN_NUMBER = 2;
TRANSACTION_INCOME_DATE_COLUMN_NUMBER = 8;
TRANSACTION_EXPENSES_ACCOUNT_COLUMN_NUMBER = 4;
TRANSACTION_INCOME_ACCOUNT_COLUMN_NUMBER = 10;
TRANSACTION_EXPENSES_CATEGORY_COLUMN_NUMBER = 6;
TRANSACTION_INCOME_CATEGORY_COLUMN_NUMBER = 12;
